"""empty message

Revision ID: 17d3cf3146aa
Revises: 2fdc39c69771
Create Date: 2016-02-07 19:09:27.116091

"""

# revision identifiers, used by Alembic.
revision = '17d3cf3146aa'
down_revision = '2fdc39c69771'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressure_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('heart_beats', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pressure_log')
    ### end Alembic commands ###
